# -*- mode: Python; coding: utf-8 -*-
#!/usr/bin/env python

from distutils.core import setup

with open('README.txt') as file:
  long_description = file.read()

from altneo4j import __version__

setup(
    name='altneo4j',

    # This is auto-generated by the
    # maven build that runs this project
    version=__version__,

    description='Alternative bindings for the embedded version of the neo4j graph database.',
    long_description=long_description,
    author='Amirouche Boubekki',
    author_email='amirouche.boubekki@gmail.com',

    url='https://github.com/amirouche/python-neo4j-embedded-alt',

    packages=(
        'altneo4j',
        'altneo4j.javalib',
    ),
    install_requires=(
      'setuptools',
    ),
    package_data={
        # Include our java dependencies
        '': ['*.jar'],
    },
    classifiers=(
        'License :: OSI Approved :: GNU General Public License (GPL)',
        'Topic :: Database :: Database Engines/Servers',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Java',
    ),
)
